version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: motor-sound-rabbitmq
    ports:
      - "5672:5672"  # RabbitMQ default port
      - "15672:15672"  # RabbitMQ management console
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: motor-sound-api
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      - ./models:/app/models
    environment:
      - MODEL_PATH=/app/models/motorsoundsmodel
      - MODEL_TYPE=gradientboosting
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq/
      - REQUEST_QUEUE=audio_processing_requests
      - RESPONSE_QUEUE=audio_processing_results
    depends_on:
      - rabbitmq
    restart: on-failure
    command: uvicorn app:app --host 0.0.0.0 --port 8000

volumes:
  rabbitmq_data:
